version: '3'

services:

  producer:
    build: ./producer
    ports:
      - "9001:8080"
    depends_on:
      - kafka
  middleman:
    build: ./middleman
    ports:
      - "9002:8080"
    depends_on:
      - kafka
  consumer:
    build: ./consumer
    ports:
      - "9003:8080"
    depends_on:
      - kafka

  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_PORT=9092
    ports:
      - "9092:9092"
      - "2181:2181"
