
spring:
  application:
      name: middleman
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          zk-nodes: kafka:2181

      bindings:
        output:
          destination: bar
