
spring:
  application:
      name: consumer-one
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          zk-nodes: kafka:2181

      bindings:
        input:
          destination: bar
